const KEY='toursplit-data-v1';
const money = n => `₹${Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const uid = () => Date.now().toString(36)+Math.random().toString(36).slice(2,7);
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{tour:null,members:[],expenses:[]};
let editing={type:null,id:null};
const $=s=>document.querySelector(s);
const save=()=>{localStorage.setItem(KEY,JSON.stringify(state));render()};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function initials(name){return (name||'?').split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function render(){
 const active=!!state.tour; $('#emptyState').hidden=active; $('#dashboard').hidden=!active;
 const total=state.expenses.reduce((a,e)=>a+Number(e.amount),0); $('#totalSpent').textContent=money(total); $('#memberCount').textContent=state.members.length; $('#expenseCount').textContent=state.expenses.length; $('#averageSpent').textContent=money(state.members.length?total/state.members.length:0);
 if(!active)return;
 $('#tourTitle').textContent=state.tour.name; $('#tourMeta').textContent=`${state.tour.start||'No start date'}${state.tour.end?' → '+state.tour.end:''} · ${state.members.length} members`; $('#tourDescription').textContent=state.tour.description||'No tour description added.';
 const shares={}; state.members.forEach(m=>shares[m.id]=0); state.expenses.forEach(e=>{if(shares[e.paidBy]!==undefined)shares[e.paidBy]+=Number(e.amount)});
 $('#settledCount').textContent=`${state.members.filter(m=>Math.abs((shares[m.id]||0)-total/(state.members.length||1))<.01).length} settled`;
 $('#balanceList').innerHTML=state.members.length?state.members.map(m=>{let balance=(shares[m.id]||0)-total/(state.members.length||1);return `<div class="balance-row"><span class="avatar">${initials(m.name)}</span><div class="row-main"><strong>${esc(m.name)}</strong><small>Paid ${money(shares[m.id]||0)}</small></div><span class="amount ${balance>=0?'positive':'negative'}">${balance>=0?'+':''}${money(balance)}</span></div>`}).join(''):'<div class="empty-list">Add members to see balances.</div>';
 $('#expenseList').innerHTML=state.expenses.length?`<div class="expense-header"><span>Description</span><span>Paid by</span><span>Amount</span><span></span></div>`+state.expenses.map(e=>{let p=state.members.find(m=>m.id===e.paidBy);return `<div class="expense-row"><div class="row-main"><strong>${esc(e.description)}</strong><small>${e.date||'No date'}${e.category?' · '+esc(e.category):''}</small></div><span class="payer">${esc(p?.name||'Unknown')}</span><span class="amount">${money(e.amount)}</span><span class="expense-actions"><button class="icon-button" onclick="editExpense('${e.id}')" title="Edit">✎</button><button class="icon-button danger" onclick="deleteExpense('${e.id}')" title="Delete">⌫</button></span></div>`}).join(''):'<div class="empty-list">No expenses yet. Add the first one.</div>';
 $('#memberList').innerHTML=state.members.length?state.members.map(m=>`<div class="member-row"><span class="avatar">${initials(m.name)}</span><div class="row-main"><strong>${esc(m.name)}</strong><small>${esc(m.email||'No email')}</small></div><button class="icon-button" onclick="editMember('${m.id}')" title="Edit">✎</button><button class="icon-button danger" onclick="deleteMember('${m.id}')" title="Delete">⌫</button></div>`).join(''):'<div class="empty-list">No members yet.</div>';
}
function openModal(title,html){$('#modalTitle').textContent=title;$('#modalForm').innerHTML=html;$('#modal').hidden=false;setTimeout(()=>$('#modalForm input')?.focus(),30)}
function closeModal(){$('#modal').hidden=true;editing={type:null,id:null}}
function actions(){return `<div class="form-actions"><button type="button" class="button secondary" id="cancelModal">Cancel</button><button class="button button-primary" type="submit">Save</button></div>`}
function tourForm(t={}){return `<div class="field"><label>Tour name *</label><input name="name" required value="${esc(t.name)}" placeholder="e.g. Kerala trip 2026"></div><div class="field"><label>Description</label><textarea name="description" placeholder="Add a note about this tour">${esc(t.description)}</textarea></div><div class="field"><label>Start date</label><input type="date" name="start" value="${t.start||''}"></div><div class="field"><label>End date</label><input type="date" name="end" value="${t.end||''}"></div>${actions()}`}
function memberForm(m={}){return `<div class="field"><label>Name *</label><input name="name" required value="${esc(m.name)}" placeholder="e.g. Rahul"></div><div class="field"><label>Email or phone</label><input name="email" value="${esc(m.email)}" placeholder="Optional contact"></div>${actions()}`}
function expenseForm(e={}){return `<div class="field"><label>Description *</label><input name="description" required value="${esc(e.description)}" placeholder="e.g. Hotel booking"></div><div class="field"><label>Amount (₹) *</label><input name="amount" required type="number" min="0.01" step="0.01" value="${e.amount||''}"></div><div class="field"><label>Paid by *</label><select name="paidBy" required><option value="">Select member</option>${state.members.map(m=>`<option value="${m.id}" ${m.id===e.paidBy?'selected':''}>${esc(m.name)}</option>`).join('')}</select></div><div class="field"><label>Category</label><input name="category" value="${esc(e.category)}" placeholder="Food, travel, stay..."></div><div class="field"><label>Date</label><input name="date" type="date" value="${e.date||new Date().toISOString().slice(0,10)}"></div>${actions()}`}
function showToast(text){let t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
$('#newTourBtn').onclick=$('#emptyNewTour').onclick=()=>{editing={type:'tour'};openModal(state.tour?'Edit tour':'Create a tour',tourForm(state.tour||{}))}; $('#editTourBtn').onclick=()=>{$('#newTourBtn').click()};
$('#deleteTourBtn').onclick=()=>{if(confirm('Delete this tour and all its members and expenses?')){state={tour:null,members:[],expenses:[]};save();showToast('Tour deleted')}};
$('#addMemberBtn').onclick=()=>{editing={type:'member'};openModal('Add member',memberForm())}; window.editMember=id=>{editing={type:'member',id};openModal('Edit member',memberForm(state.members.find(m=>m.id===id)))};
window.deleteMember=id=>{if(confirm('Delete this member? Expenses paid by them will remain as Unknown.')){state.members=state.members.filter(m=>m.id!==id);state.expenses.forEach(e=>{if(e.paidBy===id)e.paidBy=''});save();showToast('Member deleted')}};
$('#addExpenseBtn').onclick=()=>{if(!state.members.length)return showToast('Add a member first');editing={type:'expense'};openModal('Add expense',expenseForm())}; window.editExpense=id=>{editing={type:'expense',id};openModal('Edit expense',expenseForm(state.expenses.find(e=>e.id===id)))};
window.deleteExpense=id=>{if(confirm('Delete this expense?')){state.expenses=state.expenses.filter(e=>e.id!==id);save();showToast('Expense deleted')}};
$('#closeModal').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};document.addEventListener('click',e=>{if(e.target.id==='cancelModal')closeModal()});
$('#modalForm').onsubmit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));if(editing.type==='tour')state.tour={...(state.tour||{}),...d};if(editing.type==='member'){if(editing.id)Object.assign(state.members.find(x=>x.id===editing.id),d);else state.members.push({id:uid(),...d})}if(editing.type==='expense'){d.amount=Number(d.amount);if(editing.id)Object.assign(state.expenses.find(x=>x.id===editing.id),d);else state.expenses.push({id:uid(),...d})}closeModal();save();showToast('Saved successfully')};
document.querySelectorAll('.tab').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');$('#expensesTab').hidden=tab.dataset.tab!=='expenses';$('#membersTab').hidden=tab.dataset.tab!=='members'}); $('#printBtn').onclick=()=>window.print(); render();
